trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs: 
  - job: FirstJob
    steps:
    - bash: echo This is Build first job
    - bash: echo $(PipelineLevelVariable)
- stage: DevDeploy
  variables:
   environment: Dev
  jobs: 
  - job: DevFirstJob
    steps:
    - bash: echo This is $(environment) first job
  - job: SecondJob
    steps:
    - bash: echo This is $(environment) second job    
- stage: QADeploy
  variables:
   environment: QA
  jobs: 
  - job: QAFirstJob
    steps:
    - bash: echo This is $(environment)job
- stage: ProdDeploy
  variables:
   environment: PROD
  jobs: 
  - job: ProdFirstJob
    steps:
    - bash: echo This is $(environment) job
